In [1]:
import numpy as np

In [2]:
pwd

'C:\\Users\\tsuba\\git\\kaggle_study\\2_python_for_data_analysis'

In [3]:
#性能比較
my_arr=np.arange(100000000)

In [4]:
my_list=list(range(100000000))

In [7]:
%timeit my_arr2 = my_arr * 2

453 ms ± 78.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%timeit my_list2 = [x * 2 for x in my_list]

9.57 s ± 1.16 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
#一括計算
data=np.array([[1.5,-0.1,3],[0,-3,6.5]])

In [11]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [12]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [13]:
#オブジェクトのプロパティ
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

In [16]:
data.ndim

2

In [22]:
np.empty([10,10,10])

array([[[9.54616803e-312, 9.54613416e-312, 0.00000000e+000,
         2.12199579e-314, 2.14321575e-312, 2.12199579e-314,
         4.94065646e-324,             nan, 0.00000000e+000,
         6.36598743e-314],
        [2.12199579e-314, 1.69759663e-313, 2.12199579e-314,
         2.18565566e-312, 2.12199579e-314, 1.90979621e-313,
                     nan, 0.00000000e+000, 4.94065646e-322,
         2.12199579e-314],
        [4.03179200e-313, 2.12199579e-314, 3.43763318e-312,
         2.12199579e-314, 1.90979621e-313,             nan,
         0.00000000e+000, 2.12199588e-314, 2.12199579e-314,
         4.24399158e-313],
        [2.12199579e-314, 3.67105272e-312, 2.12199579e-314,
         4.94065646e-324,             nan, 0.00000000e+000,
         4.94065646e-324, 2.12199579e-314, 4.24399158e-313,
         2.12199579e-314],
        [2.56761491e-312, 2.12199579e-314, 4.94065646e-324,
                     nan, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.0000000

In [25]:
np.zeros_like([[1,2,3,4,5],[2,3,4,5,6]])

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
#ゼロ埋め
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
#arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.full([2,3],3)

array([[3, 3, 3],
       [3, 3, 3]])

In [28]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
#キャスト
arr=np.array([1,2,3])

In [30]:
arr.dtype

dtype('int64')

In [31]:
arr2=arr.astype('float')

In [32]:
arr2.dtype

dtype('float64')

In [33]:
arr2

array([1., 2., 3.])

In [35]:
data=np.array([[4,7],[0,2],[-5,6],[0,0],[1,2],[-12,-4],[3,4]])

In [36]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [37]:
data[names=='Bob']

array([[4, 7],
       [0, 0]])

In [50]:
data[names=='Bob',[0,1]]

array([4, 0])

In [52]:
data[0,1]

np.int64(7)

In [54]:
data[[0,1],1]

array([7, 2])

In [55]:
np.random.standard_normal(size=[3,3])

array([[-0.15766937, -0.64159511,  0.91401885],
       [ 0.15790457, -0.01018723,  0.18861228],
       [-0.71797141, -0.18751808,  0.39059682]])

In [57]:
rng=np.random.default_rng(seed=12345)

In [58]:
data=rng.standard_normal((2,3))

In [59]:
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

In [61]:
np.random.permutation([2,3,4])

array([4, 2, 3])

In [67]:
np.random.binomial(10,0.1,10)

array([1, 1, 2, 2, 0, 2, 0, 1, 3, 0], dtype=int32)

In [70]:
np.random.normal(10,2,10)

array([12.73242528, 12.52557662, 13.73711504,  8.99660895,  8.23102402,
       18.57987377, 11.30047577, 11.49732732, 10.73317657,  9.18879903])

In [72]:
np.random.beta(1,2)

0.316153995814877

In [73]:
x=rng.standard_normal(10)

In [74]:
y=rng.standard_normal(10)

In [76]:
np.maximum(x,y)

array([ 0.78884434,  0.6488928 ,  0.57585751,  1.39897899,  2.34740965,
        0.96849691,  0.90291934,  0.90219827, -0.15818926,  0.44948393])

In [77]:
x

array([-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,  2.34740965,
        0.96849691, -0.75938718,  0.90219827, -0.46695317, -0.06068952])

In [78]:
np.sign(1)

np.int64(1)

In [79]:
np.sign(0.1)

np.float64(1.0)